version: "3.7"
services:
  app:
    build:
      args:
        user: banzenty
        uid: 1500
      context: ./
      dockerfile: Dockerfile
    image: banzenty
    container_name: banzenty-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - banzenty

  # db:
  #   image: mysql:5.7
  #   container_name: banzenty-db
  #   restart: unless-stopped
  #   command: --max_allowed_packet=67108864
  #   environment:
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_USER: ${DB_USERNAME}
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   volumes:
  #     # - ./docker-compose/mysql:/docker-entrypoint-initdb.d
  #     - ./docker-compose/mysql/data:/var/lib/mysql
  #   networks:
  #     - banzenty

  nginx:
    image: nginx:alpine
    container_name: banzenty-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - banzenty

  # cron:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile-cron
  #   image: banzenty-cron
  #   container_name: banzenty-cron
  #   restart: unless-stopped
  #   working_dir: /var/www/
  #   volumes:
  #     - ./:/var/www
  #   networks:
  #     - banzenty

  supervisor:
    build:
      context: ./
      dockerfile: Dockerfile-supervisor
    image: banzenty-supervisor
    container_name: banzenty-supervisor
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/supervisor:/etc/supervisor/conf.d/
    networks:
      - banzenty

networks:
  banzenty:
    driver: bridge
